// Frases de las tiradas de daño (por tipo de daño) y de curación, por tramo del resultado:
// muyMal (el mínimo posible), mal, normal, bien y muyBien (el máximo posible).
export const FRASES_DANO = {
  cortante: {
    muyMal: ['El filo apenas le corta un par de hilos de la ropa.', 'Un arañazo que no merece ni una venda.', 'La hoja resbala sobre la armadura con un chirrido triste.', 'Le haces un corte tan fino que ni lo nota.', 'Afeitas, más que hieres.'],
    mal: ['Un tajo superficial que sangra poco.', 'El filo muerde, pero sin ganas.', 'Le abres un corte en el brazo, nada grave.', 'La hoja roza la carne y sigue de largo.', 'Un corte limpio, aunque pequeño.'],
    normal: ['El acero abre una herida que sangra con ganas.', 'Un tajo firme que le hace retroceder.', 'La hoja corta cuero y carne por igual.', 'Un corte profundo en el costado.', 'El filo deja su marca roja.'],
    bien: ['Un tajo brutal que salpica de rojo el suelo.', 'La hoja atraviesa la defensa y muerde hondo.', 'Le abres una herida que tardará en cerrar.', 'El corte es tan limpio que tarda un instante en sangrar.', 'Tu filo dibuja un arco carmesí en el aire.'],
    muyBien: ['Un tajo descomunal que parte el escudo y a quien lo sostiene.', 'El acero corta como si la armadura fuera papel.', 'Un golpe que separa lo que debía estar unido.', 'Tu filo canta y el enemigo grita.', 'La herida es tan terrible que hasta tus aliados apartan la mirada.'],
  },
  contundente: {
    muyMal: ['El golpe rebota como si dieras a una almohada.', 'Un empujón más que un mazazo.', 'Le das con la parte que no pega.', 'Se sacude el golpe como quien se quita el polvo.', 'Suena más fuerte de lo que duele.'],
    mal: ['Un golpe sordo que apenas le hace tambalearse.', 'Un moratón para mañana, nada más.', 'Le das, pero sin peso detrás.', 'El impacto se reparte en la armadura.', 'Un porrazo flojo.'],
    normal: ['Un golpe sólido que le corta la respiración.', 'Algo cruje con el impacto.', 'Le haces retroceder un paso.', 'El golpe resuena como un tambor.', 'Un mazazo honesto.'],
    bien: ['Un golpe demoledor que le hace doblar las rodillas.', 'Se oye el crujido de huesos.', 'El impacto le sacude hasta los dientes.', 'Le hundes la armadura de un golpe.', 'Tu arma cae como un martillo de herrero.'],
    muyBien: ['Un golpe tan brutal que el suelo tiembla bajo sus pies.', 'Sale volando contra la pared más cercana.', 'El impacto resuena por toda la sala como un trueno.', 'Le aplastas la guardia, el escudo y el orgullo.', 'Un mazazo de leyenda: hasta las piedras se agrietan.'],
  },
  perforante: {
    muyMal: ['La punta apenas se clava un dedo.', 'Un pinchazo que más parece una picadura.', 'La flecha se queda temblando en el borde del escudo.', 'La punta resbala y apenas araña.', 'Más cosquillas que herida.'],
    mal: ['Un pinchazo superficial.', 'La punta entra poco y sale enseguida.', 'Le alcanzas en una zona protegida.', 'Una herida pequeña y poco profunda.', 'El golpe se desvía al final.'],
    normal: ['La punta se clava con firmeza.', 'Un pinchazo certero que le hace gruñir.', 'La flecha acierta y se queda clavada.', 'Atraviesa el cuero y encuentra carne.', 'Una estocada limpia.'],
    bien: ['La estocada se hunde entre las placas de la armadura.', 'La flecha encuentra un hueco y se clava hasta las plumas.', 'Una perforación profunda y precisa.', 'La punta busca el punto débil y lo encuentra.', 'Tu arma atraviesa y sale por el otro lado.'],
    muyBien: ['Un golpe que atraviesa la armadura de lado a lado.', 'La flecha se le clava justo donde más duele.', 'Una estocada perfecta, directa al corazón de su defensa.', 'Tu punta encuentra el único hueco de toda su armadura.', 'La punta atraviesa de parte a parte, como una aguja la tela.'],
  },
  fuego: {
    muyMal: ['Una chispa que le chamusca un par de pelos.', 'Las llamas se apagan antes de alcanzarle.', 'Un calorcillo agradable, como de chimenea.', 'Humo y poco más.', 'Le calientas, que no es lo mismo que quemarle.'],
    mal: ['Las llamas le lamen sin mucha fuerza.', 'Un chamuscón en la ropa.', 'El fuego prende un instante y se apaga.', 'Huele a pelo quemado, poco más.', 'Una quemadura leve.'],
    normal: ['El fuego le envuelve y le arranca un grito.', 'Las llamas muerden su piel.', 'Una llamarada le hace retroceder.', 'El calor le abrasa la cara.', 'Arde, aunque no del todo.'],
    bien: ['Una columna de fuego le engulle por completo.', 'Las llamas rugen y la carne chisporrotea.', 'El fuego se le pega como una segunda piel.', 'Arde como una antorcha en mitad de la noche.', 'El calor es tan intenso que el aire tiembla.'],
    muyBien: ['Un infierno desatado: solo quedan cenizas y el eco de un grito.', 'El fuego ruge como un dragón furioso.', 'Las llamas lo consumen todo a su paso.', 'Hasta las piedras se ennegrecen con el calor.', 'Arde con la furia de los Nueve Infiernos.'],
  },
  frio: {
    muyMal: ['Una brisa fresca que casi agradece.', 'Escarcha en las cejas y poco más.', 'Un escalofrío pasajero.', 'El hielo se deshace antes de tocarle.', 'Le das frío, no daño.'],
    mal: ['El frío le entumece un poco los dedos.', 'Una capa fina de escarcha cubre su piel.', 'Tiembla un momento.', 'El hielo le roza sin morder.', 'Un frío molesto.'],
    normal: ['El hielo le muerde la piel.', 'La escarcha le cubre el pecho y le roba el aliento.', 'Sus movimientos se vuelven torpes por el frío.', 'El frío le cala hasta los huesos.', 'Le castañetean los dientes.'],
    bien: ['El hielo le envuelve y su piel se agrieta.', 'Un frío mortal le atraviesa de parte a parte.', 'La escarcha le congela la sangre en las venas.', 'Su aliento se convierte en nubes de hielo.', 'Se mueve como si cargara montañas de nieve.'],
    muyBien: ['Su cuerpo se vuelve una estatua de hielo con una mueca de horror.', 'El invierno eterno se desata sobre tu objetivo.', 'Un frío tan intenso que el aire mismo se congela.', 'Su sangre se vuelve escarcha.', 'Hasta los gigantes de escarcha temblarían.'],
  },
  relampago: {
    muyMal: ['Una chispa estática que le eriza un poco el pelo.', 'Un chasquido que suena peor de lo que es.', 'El rayo se dispersa en el suelo.', 'Un cosquilleo eléctrico.', 'Le despeinas. Eso sí.'],
    mal: ['La descarga le sacude un momento.', 'Un calambre molesto.', 'El relámpago le roza y se pierde.', 'Le tiemblan los músculos un instante.', 'Una chispa con poca fuerza.'],
    normal: ['El rayo le alcanza y le sacude de pies a cabeza.', 'Una descarga que le hace apretar los dientes.', 'La electricidad recorre su armadura.', 'Huele a ozono y a carne chamuscada.', 'Se le ponen los pelos de punta.'],
    bien: ['Un relámpago le atraviesa con un estruendo cegador.', 'La descarga le deja temblando y humeante.', 'La electricidad salta de su armadura en chispas azules.', 'Le alcanza como la ira de una tormenta.', 'Se le ilumina hasta el esqueleto.'],
    muyBien: ['Un rayo digno de los dioses de la tormenta cae sobre tu objetivo.', 'La descarga es tan brutal que queda una silueta chamuscada en el suelo.', 'El relámpago ruge y la noche se vuelve día.', 'Toda la furia del cielo en un solo impacto.', 'Su armadura brilla al rojo y las chispas llueven como estrellas.'],
  },
  trueno: {
    muyMal: ['Un estampido que solo asusta a las palomas.', 'Suena como un portazo lejano.', 'La onda le despeina, poco más.', 'Mucho ruido y pocas nueces.', 'Un eco débil.'],
    mal: ['El estruendo le hace pestañear.', 'La onda le empuja un poco.', 'Le zumban los oídos.', 'Un retumbar sordo.', 'Un golpe de sonido flojo.'],
    normal: ['El trueno le golpea como una pared invisible.', 'La onda le hace tambalearse.', 'Le pitan los oídos durante un buen rato.', 'Un estampido que retumba en su pecho.', 'El aire mismo le empuja.'],
    bien: ['Un estruendo ensordecedor que le derriba.', 'La onda le sacude hasta los huesos.', 'Las paredes tiemblan con el impacto.', 'Le revientan los tímpanos.', 'El trueno le golpea como un ariete.'],
    muyBien: ['Un estampido que sacude la tierra y rompe todos los cristales.', 'El trueno estalla como la voz de un dios furioso.', 'La onda le lanza por los aires como un muñeco.', 'El eco se oirá durante días en los valles.', 'Un rugido que deja sordo al mundo entero.'],
  },
  acido: {
    muyMal: ['Unas gotas que apenas le pican.', 'El ácido salpica al suelo y no a tu objetivo.', 'Un poco de humo y un olor desagradable.', 'Le mancha la ropa. Nada más.', 'Se evapora antes de tocarle.'],
    mal: ['El ácido le escuece en la piel.', 'Un siseo y una quemadura leve.', 'Le corroe un poco la armadura.', 'Unas manchas humeantes.', 'Quema, pero poco.'],
    normal: ['El ácido sisea al devorar su piel.', 'La armadura humea y se ablanda.', 'Un dolor punzante que no cesa.', 'Le deja la piel enrojecida y humeante.', 'El ácido muerde con ganas.'],
    bien: ['El ácido le devora carne y metal por igual.', 'Su armadura se deshace en goterones humeantes.', 'Un humo acre se eleva de sus heridas.', 'Grita mientras el ácido sigue trabajando.', 'La corrosión no tiene piedad.'],
    muyBien: ['El ácido lo disuelve todo: armadura, escudo y esperanza.', 'Un charco humeante es todo lo que queda de su defensa.', 'Hasta el suelo se deshace bajo sus pies.', 'La corrosión es tan voraz que parece tener hambre propia.', 'Las cicatrices de este ácido no se borrarán jamás.'],
  },
  veneno: {
    muyMal: ['El veneno le sienta como un trago de vino agrio.', 'Una náusea pasajera.', 'Su cuerpo neutraliza la toxina casi al instante.', 'Le duele la cabeza un rato.', 'Un mareo leve.'],
    mal: ['El veneno le revuelve el estómago.', 'Siente un ligero entumecimiento.', 'Tose y escupe, nada grave.', 'La toxina le debilita un poco.', 'Una fiebre leve le recorre.'],
    normal: ['El veneno corre por sus venas y le hace temblar.', 'Su piel palidece y le cuesta respirar.', 'La toxina le muerde por dentro.', 'Le flaquean las piernas.', 'Suda frío.'],
    bien: ['El veneno le quema por dentro como fuego líquido.', 'Sus venas se oscurecen bajo la piel.', 'Se dobla de dolor, sin aire.', 'La toxina avanza implacable.', 'Le tiemblan las manos y se le nubla la vista.'],
    muyBien: ['Un veneno tan letal que hasta las moscas huyen.', 'La toxina le recorre entero en un instante devastador.', 'Se le ennegrecen los labios y cae de rodillas.', 'Ni el mejor alquimista conoce antídoto para esto.', 'El veneno hace en un segundo lo que una enfermedad haría en un año.'],
  },
  necrotico: {
    muyMal: ['Un escalofrío de ultratumba que se disipa enseguida.', 'La sombra le roza y se desvanece.', 'Siente un leve cansancio.', 'La muerte le saluda desde lejos.', 'Un susurro frío, sin fuerza.'],
    mal: ['Su piel se vuelve grisácea un momento.', 'La energía oscura le debilita un poco.', 'Un frío extraño le recorre la espalda.', 'Siente que algo le roba el aliento.', 'Un toque sombrío y débil.'],
    normal: ['La energía necrótica le marchita la carne.', 'Su piel se oscurece y se agrieta.', 'Siente cómo la vida se le escapa.', 'Un frío de tumba le atraviesa.', 'La sombra le muerde el alma.'],
    bien: ['La muerte le acaricia y su carne se marchita.', 'Envejece años en un instante.', 'La energía oscura le drena la vida a borbotones.', 'Sus ojos pierden el brillo un instante.', 'El toque de la tumba le deja seco.'],
    muyBien: ['La propia muerte le pone la mano en el hombro.', 'Su carne se reduce a pergamino y huesos en un suspiro.', 'La energía necrótica le arranca la vida a jirones.', 'Hasta los no muertos se estremecen ante esta oscuridad.', 'Se le escapa el alma por la boca como un vaho negro.'],
  },
  radiante: {
    muyMal: ['Un destello que solo le hace entrecerrar los ojos.', 'Una luz tibia, como de amanecer nublado.', 'Brilla mucho y quema poco.', 'La luz le acaricia más que hiere.', 'Un resplandor fugaz.'],
    mal: ['La luz le escuece en la piel.', 'Un brillo molesto que le ciega un instante.', 'El resplandor le quema un poco.', 'La luz sagrada le roza.', 'Se tapa los ojos, poco más.'],
    normal: ['La luz sagrada le quema la carne.', 'Un resplandor divino le golpea de lleno.', 'Brilla tanto que le arranca un grito.', 'La luz le atraviesa como una lanza.', 'Su piel humea bajo la radiancia.'],
    bien: ['Una columna de luz le envuelve y abrasa.', 'La radiancia le purifica con dolor.', 'Brilla como si un sol naciera en su pecho.', 'La luz divina le quema hasta el alma.', 'Su sombra desaparece bajo el resplandor.'],
    muyBien: ['La luz de los dioses desciende y le abrasa sin piedad.', 'Un resplandor tan intenso que el mundo entero se vuelve blanco.', 'La radiancia le atraviesa y su silueta queda grabada en la pared.', 'Hasta las tinieblas del Abismo retroceden.', 'Un juicio divino en forma de luz pura.'],
  },
  psiquico: {
    muyMal: ['Un leve dolor de cabeza, como tras una mala noche.', 'Se le olvida qué iba a decir. Nada más.', 'Un pensamiento intruso, fácil de apartar.', 'Parpadea, confuso, y se le pasa.', 'Le zumba un poco la mente.'],
    mal: ['Un pinchazo en las sienes.', 'Se le nubla el pensamiento un instante.', 'Siente una presión molesta en la cabeza.', 'Duda de algo que antes tenía claro.', 'Le cuesta concentrarse.'],
    normal: ['El ataque psíquico le perfora la mente.', 'Se lleva las manos a la cabeza con un gemido.', 'Sus pensamientos se retuercen de dolor.', 'Le sangra la nariz por la presión mental.', 'Ve cosas que no están ahí.'],
    bien: ['Su mente se resquebraja como el cristal.', 'Grita ante visiones que nadie más puede ver.', 'Los pensamientos se le deshacen en pedazos.', 'Le estalla la cabeza de dolor.', 'Sus ojos se quedan perdidos en el vacío.'],
    muyBien: ['Su mente se rompe en mil pedazos y cada uno grita.', 'Le invades los pensamientos y siembras pesadillas eternas.', 'Un dolor psíquico tan intenso que olvida hasta su nombre.', 'Su cordura se tambalea al borde del abismo.', 'Ve el Reino Lejano un instante, y no quiere volver a verlo nunca.'],
  },
  fuerza: {
    muyMal: ['Un empujoncito mágico, casi educado.', 'La energía se disipa al tocarle.', 'Un golpe de aire con brillo.', 'Le despeinas con magia pura.', 'Apenas un roce arcano.'],
    mal: ['El impacto de fuerza le sacude un poco.', 'Un golpe invisible y flojo.', 'La energía le roza de lado.', 'Un empujón arcano sin mucho peso.', 'Lo nota, pero poco.'],
    normal: ['La fuerza pura le golpea como un puño invisible.', 'El impacto arcano le hace retroceder.', 'Un golpe de energía limpia y precisa.', 'La magia le sacude de pies a cabeza.', 'El aire vibra con el impacto.'],
    bien: ['Un impacto arcano que le hunde contra el suelo.', 'La energía pura le golpea con violencia.', 'Su armadura se abolla bajo la magia.', 'Le alcanza una fuerza que no admite defensa.', 'El impacto resuena como una campana.'],
    muyBien: ['La magia en estado puro le golpea con la fuerza de un cometa.', 'Un impacto arcano que deforma el aire a su alrededor.', 'Sale por los aires en un estallido de luz violeta.', 'No hay escudo ni armadura que frene esta energía.', 'El Tejido entero se tensa con el golpe.'],
  },
  curacion: {
    muyMal: ['Una caricia de luz que apenas cierra un rasguño.', 'Las heridas se lo piensan dos veces antes de cerrarse.', 'Un alivio leve, como un suspiro.', 'La magia sanadora titubea.', 'Un pequeño consuelo, poco más.'],
    mal: ['Las heridas más pequeñas se cierran.', 'Un poco de color vuelve a la cara.', 'Un alivio modesto.', 'La sangre deja de manar, por ahora.', 'El dolor se calma, aunque sin desaparecer.'],
    normal: ['Una luz cálida cierra las heridas.', 'El aliento vuelve con fuerza.', 'La carne se une y el dolor se aleja.', 'La energía vital fluye de nuevo.', 'Sienta tan bien como un buen descanso.'],
    bien: ['Una oleada de vida recorre el cuerpo entero.', 'Las heridas se cierran casi sin dejar marca.', 'La fuerza vuelve a los músculos de golpe.', 'Una luz dorada lo envuelve todo.', 'El dolor desaparece como la niebla al sol.'],
    muyBien: ['Un milagro: las heridas se cierran como si nunca hubieran existido.', 'La vida rebosa y hasta las cicatrices viejas se borran.', 'La luz sanadora brilla como un amanecer.', 'Se siente mejor que antes de la batalla.', 'Los dioses han escuchado tu súplica.'],
  },
};
