// Frases de las pruebas de habilidad, por habilidad y por tramo del resultado:
// muyMal (1 natural), mal, normal, bien y muyBien (20 natural). En segunda persona y sin género.
export const FRASES_HABILIDAD = {
  acrobacias: {
    muyMal: ['Tus pies se enredan entre sí y besas el suelo con todo el cuerpo.', 'Intentas una voltereta y aterrizas de espaldas, con un crujido que se oye en toda la sala.', 'El equilibrio te abandona a medio salto. El suelo no.', 'Resbalas en lo único húmedo de toda la estancia.', 'Giras en el aire con gracia… y caes como un saco de patatas.'],
    mal: ['Trastabillas y tienes que agarrarte a lo primero que encuentras.', 'El salto se queda corto; te salvas por un pelo y sin ninguna elegancia.', 'Te tambaleas demasiado: cualquiera diría que es la primera vez.', 'Aterrizas, sí, pero con las rodillas protestando.', 'La cornisa es más estrecha de lo que parecía, y tus pies lo notan.'],
    normal: ['Mantienes el equilibrio sin alardes, paso a paso.', 'Ruedas por el suelo y te levantas sin perder el ritmo.', 'Un salto limpio, aunque nadie lo aplaudiría.', 'Cruzas con cuidado, brazos abiertos, sin mirar abajo.', 'Esquivas el obstáculo con lo justo y sigues adelante.'],
    bien: ['Danzas sobre la viga como si fuera un camino real.', 'Una pirueta precisa te deja justo donde querías.', 'Tu cuerpo responde antes que tu mente: ligero, exacto.', 'Te deslizas entre los obstáculos como el agua entre las piedras.', 'Aterrizas en cuclillas, sin un ruido, con todo a punto para lo siguiente.'],
    muyBien: ['Volteretas, giros y un aterrizaje perfecto. Los bardos cantarán este salto.', 'Corres por la pared, giras en el aire y caes de pie como un felino.', 'La gravedad parece haberte concedido una tregua solo a ti.', 'Cada movimiento encadena con el siguiente: una danza imposible.', 'Hasta el viento se aparta para no estorbar tu acrobacia.'],
  },
  arcanos: {
    muyMal: ['Confundes un círculo de invocación con un mantel muy elaborado.', 'Juras que esas runas significan «paz». Significan otra cosa. Mucho peor.', 'Tu explicación de la magia arrancaría lágrimas a cualquier archimago… de vergüenza.', 'Lees el glifo del revés y casi lo activas.', 'La teoría arcana se te escapa como arena entre los dedos.'],
    mal: ['Reconoces la escuela de magia, pero poco más.', 'Esos símbolos te suenan de algún libro que no terminaste de leer.', 'Tu memoria arcana está llena de lagunas justo donde no debería.', 'Intuyes que es peligroso. Eso lo sabría cualquiera.', 'Recuerdas a medias una lección que no prestaste atención.'],
    normal: ['Identificas la escuela de magia y la intención del hechizo.', 'Las runas cuentan una historia que, más o menos, entiendes.', 'Recuerdas un tratado que describe algo parecido.', 'El flujo del Tejido es reconocible, aunque no del todo claro.', 'Sabes lo suficiente para no tocarlo sin pensar.'],
    bien: ['El patrón arcano se despliega ante tus ojos como un mapa abierto.', 'Recitas de memoria el nombre del encantamiento y quién suele usarlo.', 'Ves las costuras del Tejido donde otros solo ven luz.', 'Identificas el hechizo, su nivel y el error de quien lo lanzó.', 'Tu erudición arcana impresionaría a un tribunal de magos.'],
    muyBien: ['El Tejido te susurra sus secretos como a un viejo amigo.', 'Comprendes la magia hasta su raíz: quién la tejió, cuándo y por qué.', 'Las runas brillan al leerlas, como si te reconocieran.', 'Desentrañas en un instante lo que a otros les costaría una vida.', 'Por un momento, toda la geometría de la magia cabe en tu mente.'],
  },
  atletismo: {
    muyMal: ['Tomas impulso, saltas… y te estampas contra el muro con dignidad cero.', 'La cuerda se te escurre de las manos y caes de culo.', 'Empujas con todas tus fuerzas. La puerta ni se inmuta. Tú sí.', 'Te enredas en tus propias piernas en mitad de la carrera.', 'Nadas como una piedra. Una piedra muy decidida.'],
    mal: ['Trepas medio metro y resbalas otro tanto.', 'El agarre no es firme; tu rival se zafa con facilidad.', 'Saltas con todo, pero el borde queda a un palmo de tus dedos.', 'Los músculos arden y el avance es mínimo.', 'Empujas, resoplas y apenas consigues moverlo.'],
    normal: ['Trepas con esfuerzo, apoyo a apoyo, hasta arriba.', 'Un salto decente que te deja al otro lado.', 'Sujetas con firmeza lo justo para no soltarlo.', 'Nadas contra la corriente y ganas la orilla.', 'Con un gruñido, lo levantas lo suficiente.'],
    bien: ['Escalas la pared como si tuviera escalones tallados.', 'Tu salto cubre la distancia con margen de sobra.', 'Agarras a tu oponente y no hay forma de que se suelte.', 'La puerta cede con un golpe de hombro bien dado.', 'Tus músculos responden como cuerdas de arco tensas.'],
    muyBien: ['Saltas el abismo de un impulso y aterrizas sin perder el paso.', 'Levantas la roca sobre tu cabeza ante la mirada atónita de todos.', 'Trepas el acantilado a una velocidad que asusta a las cabras.', 'Tu agarre es de hierro: nada en este mundo lo rompería.', 'Por un instante, tu fuerza parece la de un gigante.'],
  },
  engano: {
    muyMal: ['Te contradices en la misma frase. Dos veces.', 'Tu sonrisa nerviosa delata la mentira antes de que acabes.', 'Mientes con tanto detalle que es obvio que mientes.', 'Se te escapa la verdad justo en la última palabra.', 'Hasta el perro del guardia sabe que estás mintiendo.'],
    mal: ['La historia tiene un agujero en el que cabe un carro.', 'Te miran con una ceja levantada que no presagia nada bueno.', 'Tu voz tiembla en el peor momento.', 'Suena casi creíble. Casi.', 'Te creen a medias, y eso es peor que nada.'],
    normal: ['La mentira cuela, aunque nadie la recordará como tu obra maestra.', 'Mantienes la cara seria y la historia aguanta.', 'Te escuchan sin sospechar demasiado.', 'Una media verdad bien colocada hace el trabajo.', 'Nadie te aplaude, pero nadie te descubre.'],
    bien: ['Cada palabra encaja: la historia suena a pura verdad.', 'Mientes mirando a los ojos, y te dan las gracias.', 'Tu engaño es tan fino que hasta tú casi te lo crees.', 'Asienten convencidos, sin una sola duda.', 'La trampa verbal se cierra sin que la vean venir.'],
    muyBien: ['Tejes una mentira tan perfecta que mañana la contarán como historia.', 'Te creen tanto que acaban defendiendo tu versión ante otros.', 'Ni un dios de la verdad encontraría la grieta en tu relato.', 'Convences a tu víctima de que la idea fue suya desde el principio.', 'La mentira más hermosa jamás contada en esta taberna.'],
  },
  historia: {
    muyMal: ['Mezclas tres reinos, dos guerras y un rey que nunca existió.', 'Atribuyes la batalla al bando equivocado con total seguridad.', 'Tu lección de historia haría llorar a cualquier cronista.', 'Juras que ese castillo es antiquísimo. Lo construyeron el año pasado.', 'Recuerdas fechas, nombres y lugares… todos mal.'],
    mal: ['Te suena el nombre, pero no sabrías decir de qué.', 'Recuerdas una canción sobre ello, más leyenda que verdad.', 'Tu memoria histórica tiene más niebla que un pantano.', 'Sabes que pasó algo importante aquí. Poco más.', 'Confundes al héroe con su enemigo durante un rato.'],
    normal: ['Recuerdas lo esencial: quién, cuándo y por qué.', 'Las crónicas que leíste te dan una idea razonable.', 'Reconoces el blasón de una casa noble venida a menos.', 'La historia de este lugar te viene a la memoria a grandes rasgos.', 'Sabes lo que cualquier persona instruida sabría.'],
    bien: ['Recitas el linaje completo de la casa y sus alianzas.', 'Recuerdas un detalle olvidado que cambia el sentido de todo.', 'Las ruinas te hablan: reconoces su época y su estilo.', 'Citas de memoria un pasaje de una crónica antigua.', 'Conectas el presente con un hecho de hace siglos.'],
    muyBien: ['Recuerdas lo que ni los propios cronistas quisieron escribir.', 'Reconoces la marca de un imperio perdido que todos creían leyenda.', 'La historia entera de este lugar se despliega en tu mente como un tapiz.', 'Sabes más de esta dinastía que sus propios herederos.', 'Un dato olvidado de tu memoria resuelve un misterio de siglos.'],
  },
  interpretacion: {
    muyMal: ['Se te rompe la cuerda del laúd… y la voz… y la dignidad.', 'Olvidas la letra a mitad de canción y tarareas con desesperación.', 'Tu actuación provoca risas, pero no las que buscabas.', 'Alguien lanza una verdura. Luego otra.', 'El público se va antes del estribillo.'],
    mal: ['Desafinas en las notas altas y el público lo nota.', 'Los aplausos son escasos y por compromiso.', 'Tu baile tiene más tropiezos que pasos.', 'La historia que narras se pierde a la mitad.', 'Alguien bosteza en primera fila.'],
    normal: ['Una actuación correcta que arranca algunos aplausos.', 'La melodía es agradable y nadie se queja.', 'Cuentas la historia con soltura y el público escucha.', 'Te ganas unas monedas y alguna sonrisa.', 'Cumples, y la taberna sigue a lo suyo.'],
    bien: ['El público contiene el aliento en cada pausa.', 'Tu voz llena la sala y acalla las conversaciones.', 'Los pies de todos siguen el ritmo de tu música.', 'Arrancas lágrimas en el verso triste y risas en el alegre.', 'Te piden otra, y otra más.'],
    muyBien: ['La sala entera se pone en pie: es una actuación que se recordará durante generaciones.', 'Tu canción hace llorar al tabernero, que jura no haber llorado nunca.', 'Por un momento, el mundo entero baila a tu compás.', 'Hasta los fantasmas del lugar se asoman a escucharte.', 'Las monedas llueven sobre el escenario como granizo dorado.'],
  },
  intimidacion: {
    muyMal: ['Tu amenaza suena tan ridícula que se echan a reír.', 'Golpeas la mesa para impresionar y te haces daño en la mano.', 'Gruñes con fuerza… y te atragantas.', 'Te miran con lástima, que es lo contrario del miedo.', 'Tu mirada feroz provoca ternura.'],
    mal: ['Ni se inmutan. Quizá un pestañeo.', 'Tu tono amenazante se queda en un enfado leve.', 'Te escuchan con más paciencia que miedo.', 'La amenaza no termina de sonar creíble.', 'Retroceden un paso por cortesía, nada más.'],
    normal: ['Captas su atención: ahora te toman en serio.', 'Un silencio incómodo sigue a tus palabras.', 'Tragan saliva y bajan un poco la voz.', 'Tu presencia basta para que se lo piensen dos veces.', 'Ceden, aunque sin mucho entusiasmo.'],
    bien: ['Palidecen y apartan la mirada.', 'Tu voz, baja y fría, les eriza la piel.', 'Sueltan el arma antes de darse cuenta.', 'Te dan lo que pides sin rechistar.', 'El miedo se les nota en el temblor de las manos.'],
    muyBien: ['Tu sola mirada hace que huyan sin mirar atrás.', 'Confiesan hasta lo que no les has preguntado.', 'Hasta la llama de las velas parece encogerse ante ti.', 'Se arrodillan y suplican antes de que termines la frase.', 'Contarán tu nombre en susurros, para asustar a los niños.'],
  },
  investigacion: {
    muyMal: ['Revuelves todo y destruyes la única pista que había.', 'Encuentras una conclusión brillante. Completamente errónea.', 'Te pasas una hora examinando la pared equivocada.', 'Tu deducción señala con firmeza a la persona inocente.', 'Activas el mecanismo que intentabas comprender.'],
    mal: ['Encuentras algo, pero no sabes qué significa.', 'Las pistas están ahí; tú no terminas de verlas.', 'Tu razonamiento cojea a mitad de camino.', 'Pasas por alto el detalle que lo explicaba todo.', 'Sacas una conclusión precipitada.'],
    normal: ['Encuentras la pista evidente y la entiendes.', 'Tu razonamiento llega a una conclusión sensata.', 'Hallas el compartimento, aunque te cuesta abrirlo.', 'Las piezas empiezan a encajar.', 'Un examen minucioso da sus frutos.'],
    bien: ['Una marca diminuta te revela el mecanismo oculto.', 'Unes las pistas con una lógica impecable.', 'El documento tiene un doble fondo… y lo encuentras.', 'Deduces quién estuvo aquí y qué buscaba.', 'Tu mente analítica separa lo importante de lo accesorio.'],
    muyBien: ['Lo ves todo: cada pista, cada mentira, cada movimiento.', 'Resuelves el enigma antes de que los demás lo entiendan.', 'Encuentras el secreto que nadie había descubierto en siglos.', 'Tu deducción es tan precisa que parece adivinación.', 'Reconstruyes los hechos como si los hubieras presenciado.'],
  },
  juegomanos: {
    muyMal: ['La bolsa se rompe y las monedas tintinean por todo el suelo.', 'Tu mano queda atrapada justo en el bolsillo equivocado.', 'El naipe escondido cae de tu manga delante de todos.', 'Rozas la ganzúa contra la cerradura con un chirrido delator.', 'Te descubren con las manos literalmente en la masa.'],
    mal: ['Un movimiento torpe que más de uno ha visto.', 'Rozas a tu víctima y se lleva la mano al cinto.', 'El objeto se te resbala y lo recuperas a duras penas.', 'Lo consigues, pero alguien te mira con sospecha.', 'Tus dedos van más lentos que tu ambición.'],
    normal: ['Un gesto rápido y el objeto cambia de dueño.', 'Nadie parece haber notado nada.', 'El truco sale, sin florituras.', 'Escondes el objeto con un movimiento natural.', 'Tus dedos hacen su trabajo sin llamar la atención.'],
    bien: ['Tus dedos se mueven más rápido que la vista.', 'La bolsa desaparece y tu víctima sigue sonriendo.', 'El truco es tan limpio que parece magia.', 'Cambias el objeto por otro sin que nadie lo note.', 'Ni el guardia más atento vería lo que acabas de hacer.'],
    muyBien: ['Le robas el anillo del dedo mientras te da la mano.', 'Tus manos son un susurro: nadie sabrá nunca lo que pasó.', 'Vacías tres bolsillos y dejas una moneda de propina.', 'El ladrón más famoso del gremio querría ser tu aprendiz.', 'Un movimiento tan perfecto que hasta tú dudas de haberlo hecho.'],
  },
  medicina: {
    muyMal: ['Vendas la herida equivocada con mucho empeño.', 'Tu diagnóstico: «está malito». Muy útil.', 'Aplicas la hierba venenosa en lugar de la curativa.', 'La venda se suelta en cuanto te das la vuelta.', 'Tu remedio empeora las cosas de forma espectacular.'],
    mal: ['Detienes la hemorragia, pero a duras penas.', 'Sabes que algo va mal; no sabes qué.', 'El vendaje aguanta… más o menos.', 'Tu diagnóstico es vago e inseguro.', 'Haces lo que puedes, que no es mucho.'],
    normal: ['Estabilizas al herido con un vendaje firme.', 'Reconoces los síntomas de una dolencia común.', 'La herida se limpia y deja de sangrar.', 'Sabes qué hierba usar y cómo prepararla.', 'Un trabajo correcto, de manual de campaña.'],
    bien: ['Tus manos expertas cierran la herida con precisión.', 'Identificas el veneno por el color de la piel.', 'El herido respira mejor en cuanto terminas.', 'Tu diagnóstico es certero y tu tratamiento, impecable.', 'Ni un cirujano del templo lo habría hecho mejor.'],
    muyBien: ['Arrancas a alguien de las garras de la muerte con hilo y aguja.', 'Diagnosticas la causa exacta, el origen y la cura en un vistazo.', 'Tu cuidado es tan preciso que casi parece un milagro.', 'Hasta los clérigos se acercan a ver cómo lo haces.', 'La herida se cierra limpia, sin dejar apenas cicatriz.'],
  },
  naturaleza: {
    muyMal: ['Juras que esa seta es comestible. No lo es.', 'Confundes un oso con un tejón muy grande.', 'Predices sol radiante justo antes de la tormenta.', 'Llamas «árbol» a un ent. No le hace gracia.', 'Tu conocimiento de la naturaleza se limita a «verde» y «no verde».'],
    mal: ['Reconoces la planta, pero no sus propiedades.', 'Ese rastro podría ser de cualquier cosa con patas.', 'Tus recuerdos del bosque son confusos.', 'Intuyes que el tiempo va a cambiar. Poco más.', 'Sabes que ese animal es peligroso por su tamaño.'],
    normal: ['Identificas la planta y sabes para qué sirve.', 'Reconoces las costumbres de esta criatura.', 'El cielo te dice que lloverá antes del anochecer.', 'Sabes qué bayas comer y cuáles evitar.', 'El terreno no guarda secretos importantes para ti.'],
    bien: ['Lees el bosque como un libro abierto.', 'Reconoces la criatura, su dieta y su punto débil.', 'Sabes por el musgo dónde está el agua más cercana.', 'Detectas la planta medicinal escondida entre la maleza.', 'Los ciclos de la naturaleza no tienen misterio para ti.'],
    muyBien: ['La naturaleza parece hablarte en un idioma que solo tú entiendes.', 'Sabes, por el vuelo de los pájaros, que algo grande se acerca.', 'Identificas una especie que los sabios creían extinta.', 'Cada hoja, cada huella y cada brisa te cuentan su historia.', 'Hasta los druidas te pedirían consejo.'],
  },
  percepcion: {
    muyMal: ['Miras a todas partes menos al dragón que tienes delante.', 'Confundes el aullido del lobo con el viento. Y el viento con un lobo.', 'Ni un ejército con tambores llamaría tu atención ahora mismo.', 'Te distrae una mariposa en el peor momento.', 'Tus ojos están abiertos; tu atención, de vacaciones.'],
    mal: ['Algo se mueve en la sombra… o quizá no.', 'Oyes un ruido, pero no sabes de dónde viene.', 'Se te escapan los detalles importantes.', 'Tu vista recorre la sala sin ver lo esencial.', 'Tienes la sensación de que algo no encaja.'],
    normal: ['Notas lo que hay que notar, ni más ni menos.', 'Un ruido a tu izquierda capta tu atención.', 'Ves las huellas recientes en el barro.', 'Algo brilla entre los escombros.', 'Tus sentidos alerta te dan una idea clara del lugar.'],
    bien: ['Captas el leve chasquido de una ballesta al tensarse.', 'Ves el destello de unos ojos en la oscuridad.', 'Notas la corriente de aire que delata una puerta secreta.', 'Hueles el humo antes de verlo.', 'Ningún detalle de la sala escapa a tu mirada.'],
    muyBien: ['Oyes el latido de quien se esconde tras la pared.', 'Tus sentidos lo captan todo: cada paso, cada sombra, cada respiración.', 'Ves la trampa, el asesino escondido y la salida oculta a la vez.', 'Nada se mueve en un kilómetro a la redonda sin que lo sepas.', 'Tu percepción roza lo sobrenatural.'],
  },
  perspicacia: {
    muyMal: ['Te parece la persona más sincera del mundo. Te está mintiendo.', 'Lees miedo donde solo hay hambre.', 'Confías justo en quien no deberías.', 'Interpretas su sonrisa como amistad. Es todo lo contrario.', 'Tu instinto te grita la conclusión equivocada.'],
    mal: ['No sabes si dice la verdad; parece nervioso por algo.', 'Hay algo raro en su mirada, pero no lo descifras.', 'Su tono te desconcierta.', 'Intuyes que oculta algo, sin saber qué.', 'Te cuesta leer sus intenciones.'],
    normal: ['Notas que está incómodo con la pregunta.', 'Sus gestos dicen más que sus palabras.', 'Te da la impresión de que no te lo cuenta todo.', 'Lees su estado de ánimo con bastante claridad.', 'Su mentira tiene costuras visibles.'],
    bien: ['Ves la mentira en el temblor de su labio.', 'Comprendes lo que de verdad busca.', 'Su miedo es evidente para ti, aunque lo disimule.', 'Sabes exactamente qué le preocupa.', 'Lees entre líneas cada una de sus palabras.'],
    muyBien: ['Lees su alma como si estuviera escrita en su frente.', 'Sabes lo que va a decir antes de que abra la boca.', 'Descubres su secreto más profundo con una sola mirada.', 'Ninguna máscara resistiría tu escrutinio.', 'Ves la verdad desnuda tras cada gesto y cada pausa.'],
  },
  persuasion: {
    muyMal: ['Tu discurso convence a todos… de lo contrario.', 'Ofendes a tu interlocutor en la primera frase.', 'Te enredas tanto en tus argumentos que acabas pidiendo perdón.', 'Llamas al barón por el nombre de su enemigo.', 'Tras tu intervención, la negociación está peor que antes.'],
    mal: ['Te escuchan sin mucho interés.', 'Tus argumentos no terminan de convencer.', 'Asienten por educación, pero no ceden.', 'Consigues muy poco a cambio de mucho.', 'Tu entusiasmo no es contagioso.'],
    normal: ['Llegáis a un acuerdo razonable.', 'Tus palabras suenan sensatas y te escuchan.', 'Ceden en lo importante, aunque no en todo.', 'Tu tono amable abre una puerta.', 'Te dan una oportunidad.'],
    bien: ['Tus palabras desarman cualquier objeción.', 'Te ofrecen más de lo que pedías.', 'Convences con una calidez irresistible.', 'Hasta el más terco termina asintiendo.', 'Ganas un aliado donde había un desconocido.'],
    muyBien: ['Tu discurso es tan inspirador que te seguirían a la guerra.', 'Consigues un trato que los mercaderes estudiarán durante años.', 'Conviertes a un enemigo en un amigo leal.', 'Las puertas, los corazones y los cofres se abren a tu paso.', 'Hasta el rey asiente y pide que repitas tus palabras.'],
  },
  religion: {
    muyMal: ['Rezas a la deidad equivocada en el templo equivocado.', 'Confundes un símbolo sagrado con uno profano. Ante sus fieles.', 'Tu interpretación del rito provoca escándalo.', 'Recitas una plegaria que en realidad es una maldición.', 'Tu teología haría desmayarse a un sumo sacerdote.'],
    mal: ['Reconoces que es un símbolo religioso. Poco más.', 'La deidad te suena de alguna festividad.', 'Recuerdas fragmentos inconexos de la liturgia.', 'Intuyes que es sagrado, o quizá maldito.', 'Tu conocimiento de los dioses es superficial.'],
    normal: ['Identificas la deidad y su dominio.', 'Reconoces el rito y su propósito.', 'Sabes qué ofende y qué honra a este culto.', 'Recuerdas lo que se enseña en cualquier templo.', 'El símbolo te habla de una fe que conoces.'],
    bien: ['Recitas de memoria los preceptos de este culto.', 'Reconoces una herejía sutil en el altar.', 'Sabes qué no-muerto teme este símbolo y por qué.', 'Los secretos del culto se te revelan con claridad.', 'Tu conocimiento sagrado impresionaría a un clérigo.'],
    muyBien: ['Por un instante, sientes la mirada de los dioses sobre ti.', 'Desentrañas un misterio teológico de siglos.', 'Reconoces el nombre verdadero de una deidad olvidada.', 'Los fieles te miran como si fueras un profeta.', 'Comprendes el plan divino detrás de lo que ocurre.'],
  },
  sigilo: {
    muyMal: ['Pisas una rama, tropiezas con un cubo y estornudas. Todo a la vez.', 'Tu armadura tintinea como una campana de templo.', 'Te escondes tras una cortina… con los pies a la vista.', 'Te escondes detrás del único guardia que estaba mirando.', 'Hasta los sordos se giran a mirarte.'],
    mal: ['Un crujido delata tu posición por un momento.', 'Te mueves, pero tu sombra te traiciona.', 'El guardia frunce el ceño y mira hacia ti.', 'Avanzas a duras penas sin que se den cuenta.', 'Tu respiración suena demasiado fuerte.'],
    normal: ['Te deslizas entre las sombras sin llamar la atención.', 'Avanzas despacio, sin hacer ruido.', 'Nadie se fija en ti al pasar.', 'Te escondes en un buen rincón.', 'Un paso tras otro, silencioso y prudente.'],
    bien: ['Eres una sombra más entre las sombras.', 'Pasas junto al guardia sin que pestañee.', 'Ni el polvo se levanta a tu paso.', 'Te desvaneces en la oscuridad como el humo.', 'Tu silencio es absoluto.'],
    muyBien: ['Te mueves como un susurro: ni los perros te huelen.', 'Cruzas el campamento enemigo entero y vuelves con un recuerdo.', 'Podrías bailar en el salón del trono sin que nadie te viera.', 'La propia noche te envidia.', 'Nadie sabrá nunca que estuviste aquí.'],
  },
  supervivencia: {
    muyMal: ['Sigues el rastro con decisión. En círculo. Tres veces.', 'Plantas el campamento en el cauce seco de un río. Llueve.', 'Confundes el norte con… algo que no es el norte.', 'Encuentras huellas: son las tuyas.', 'Tu fuego humea más que calienta.'],
    mal: ['El rastro se pierde entre las piedras.', 'Encuentras comida, aunque escasa y poco apetitosa.', 'Dudas del camino más de lo que te gustaría.', 'Las huellas son confusas y antiguas.', 'Sobrevives, pero sin ningún lujo.'],
    normal: ['Sigues el rastro sin perderlo.', 'Encuentras agua y un buen refugio para la noche.', 'Te orientas por las estrellas sin problema.', 'Cazas lo suficiente para todo el grupo.', 'Sabes por dónde ir y por dónde no.'],
    bien: ['Las huellas te cuentan cuántos son, cuándo pasaron y adónde van.', 'Encuentras un sendero oculto que ahorra horas de viaje.', 'Tu campamento es seguro, seco y bien escondido.', 'Predices el cambio de tiempo con un día de antelación.', 'La tierra salvaje es tu casa.'],
    muyBien: ['Sigues un rastro de hace días sobre la roca desnuda.', 'Sabes qué comió la presa, si estaba herida y cuánto falta para alcanzarla.', 'Guías al grupo por la tormenta sin perder un solo paso.', 'La naturaleza no tiene secretos para ti.', 'Hasta los exploradores élficos tomarían notas.'],
  },
  tratoanimales: {
    muyMal: ['Intentas acariciar al caballo y te muerde con ganas.', 'El perro decide que tu pierna es su enemiga.', 'El animal huye espantado… llevándose tus provisiones.', 'Tu silbido tranquilizador suena a desafío.', 'Hasta el gato de la posada te bufa.'],
    mal: ['El animal te mira con desconfianza.', 'Se calma un poco, pero sigue nervioso.', 'Obedece a regañadientes, si es que obedece.', 'Tus gestos no terminan de convencerlo.', 'Mantiene las distancias.'],
    normal: ['El animal se tranquiliza a tu lado.', 'Te deja acercarte sin problemas.', 'Responde a tu orden, aunque sin entusiasmo.', 'Entiendes lo que le inquieta.', 'Con paciencia, consigues que te siga.'],
    bien: ['El animal se acerca y apoya la cabeza en tu mano.', 'Te obedece como si fuerais viejos amigos.', 'Calmas a la bestia con unas pocas palabras.', 'Entiendes cada uno de sus gestos.', 'El caballo más bravo se vuelve dócil contigo.'],
    muyBien: ['La bestia salvaje se tumba a tus pies como un cachorro.', 'Los animales del bosque parecen reconocerte como uno de los suyos.', 'Hasta el lobo alfa inclina la cabeza ante ti.', 'Entre tú y el animal nace un vínculo instantáneo.', 'Te sigue con una lealtad que no se puede comprar.'],
  },
};
