// Aumento de característica de cada dote general y don épico (Manual del Jugador de 2024 y Héroes de Faerûn):
// qué características puede subir en 1. Sirve cuando no se ha importado el libro con el texto de la dote.
const T = ['fue', 'des', 'con', 'int', 'sab', 'car'];
export const AUMENTO_DOTE = {
  'acechador': ['des'],
  'actor': ['car'],
  'apresador': ['fue', 'des'],
  'atacante a la carga': ['fue', 'des'],
  'atleta': ['fue', 'des'],
  'azote de magos': ['fue', 'des'],
  'centinela': ['fue', 'des'],
  'chef': ['con', 'sab'],
  'colaboracion de los arpistas': ['des', 'car'],
  'comandante del dragon purpura': ['fue', 'des'],
  'combatiente con dos armas': ['fue', 'des'],
  'combatiente montado': ['fue', 'des', 'sab'],
  'conjurador de frio': ['int', 'sab', 'car'],
  'determinacion senorial': ['fue', 'car'],
  'don de la absorcion de almas': T,
  'don de la comunicacion': ['int', 'sab', 'car'],
  'don de la fortaleza': T,
  'don de la furia de la tormenta': ['int', 'sab', 'car'],
  'don de la habilidad': T,
  'don de la pericia en combate': T,
  'don de la recuperacion': T,
  'don de la resistencia a energias': T,
  'don de la resistencia desesperada': ['fue', 'con'],
  'don de la salud plena': T,
  'don de la velocidad': T,
  'don de la vision verdadera': T,
  'don de las formas fluidas': ['int', 'sab', 'car'],
  'don del ataque imparable': ['fue', 'des'],
  'don del derramamiento de sangre': T,
  'don del destino': T,
  'don del dominio de los venenos': T,
  'don del espiritu de la noche': T,
  'don del favor de la fortuna': T,
  'don del fulgor exquisito': T,
  'don del jolgorio': ['int', 'sab', 'car'],
  'don del recuerdo de conjuros': ['int', 'sab', 'car'],
  'don del sol brillante': ['con', 'sab', 'car'],
  'don del terror': ['car'],
  'don del viaje dimensional': T,
  'dracosenalado': ['con', 'car'],
  'duelista defensivo': ['des'],
  'embaucador feerico': ['des', 'car'],
  'entrenamiento con armas marciales': ['fue', 'des'],
  'envenenador': ['des', 'int'],
  'experto en ballestas': ['des'],
  'experto en habilidades': T,
  'influencia feerica': ['int', 'sab', 'car'],
  'influencia sombria': ['int', 'sab', 'car'],
  'justicia callejera': ['fue', 'des'],
  'lanzador en combate': ['int', 'sab', 'car'],
  'lanzador preciso': ['int', 'sab', 'car'],
  'lanzador ritual': ['int', 'sab', 'car'],
  'lider inspirador': ['sab', 'car'],
  'ligeramente acorazado': ['fue', 'des'],
  'maestro de armas': ['fue', 'des'],
  'maestro en armaduras medias': ['fue', 'des'],
  'maestro en armaduras pesadas': ['fue', 'con'],
  'maestro en armas de asta': ['fue', 'des'],
  'maestro en armas pesadas': ['fue'],
  'maestro en escudos': ['fue'],
  'magia de genio': ['int', 'sab', 'car'],
  'magia del enclave': ['int', 'sab', 'car'],
  'mente aguda': ['int'],
  'moderadamente acorazado': ['fue', 'des'],
  'muy acorazado': ['fue', 'con'],
  'observador': ['int', 'sab'],
  'perforador': ['fue', 'des'],
  'rebanador': ['fue', 'des'],
  'resiliente': T,
  'resistencia de la orden': ['fue', 'sab', 'car'],
  'resistente': ['con'],
  'tacticas de los zhentarim': ['des', 'car'],
  'telepatico': ['int', 'sab', 'car'],
  'telequinetico': ['int', 'sab', 'car'],
  'tirador de primera': ['des'],
  'tocado por los mythales': ['int', 'sab', 'car'],
  'triturador': ['fue', 'con'],
  'veloz': ['des', 'con'],
  'versado en el fuego magico': ['int', 'sab', 'car'],
  'versado en un elemento': ['int', 'sab', 'car'],
};
